---
title: "dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))

set.seed(1)

data("rest_inspec")
rest_inspec = rest_inspec %>% 
  filter(inspection_date > "1900-01-01",
         boro != "Missing") %>% 
  drop_na(score)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Mean score distribution

```{r, echo = FALSE}
rest_inspec %>% 
  group_by(boro, camis) %>% 
  summarise(mean_score = mean(score)) %>% 
  plot_ly(x = ~mean_score, type = "histogram", 
          color = ~fct_reorder(boro, desc(mean_score)), alpha = .5) %>% 
  layout(
    title = "Mean score distribution",
    xaxis = list(title = "Mean score"),
    yaxis = list(title = "Count"),
    barmode = "overlay"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of inspections per day

```{r, echo = FALSE}
rest_inspec %>%
  group_by(inspection_date, boro) %>% 
  summarise(n = n()) %>%
  plot_ly(x = ~inspection_date, y = ~n, type = "scatter", mode = "markers",
          color = ~fct_reorder(boro, desc(n)), alpha = .5) %>% 
  layout(
    title = "Number of inspections per day",
    xaxis = list(title = "Inspection date"),
    yaxis = list(title = "Number of inspections")
  )
```

### Scores of top 5 most common cuisine types

```{r, echo = FALSE}
pop_cuisine =
  rest_inspec %>% 
  count(cuisine_description, sort = TRUE) %>% 
  top_n(5) %>% 
  select(cuisine_description)

inner_join(rest_inspec, pop_cuisine, by = "cuisine_description") %>% 
  plot_ly(y = ~score, x = ~boro, color = ~cuisine_description, 
          type = "box", alpha = .5) %>% 
  layout(
    title = "Scores of top 5 most common cuisine types",
    xaxis = list(title = "Boro"),
    yaxis = list(title = "Score"),
    boxmode = "group"
  )
```

